### ISSUE TITLE
ox-ipynb.el is missing a  (require 'dash)  ?

### ISSUE THREAD

**Issue by thw5858** [jkitchin/ox-ipynb#24]
At least adding the line  
(require 'dash)
stopped ox-ipynb from complaining about missing -sequence and -constains?
(btw, searching for the latter string is really painful on search engines :-/)

Thanks for the package which will save me from using emacs-ipython-notebook.

Thomas

**Comment by jkitchin** [comment]
Thanks for reporting this. I added that line.
