### ISSUE TITLE
#+TOC: headlines 1 causes notebook export failure

### ISSUE THREAD

**Issue by uliw** [jkitchin/ox-ipynb#35]
Hi John,

the following example:
```
#+TOC: headlines 1

some text
```
fails with
```
funcall: Symbol’s function definition is void: ox-ipynb-keyword-link
```

This is on a new install, GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.20), Org 9.4

**Comment by jkitchin** [comment]
Indeed. I don't remember why that is there, and can't find it in the history, so I removed it.
