### ISSUE TITLE
#+begin_export latex is not exported

### ISSUE THREAD

**Issue by Morazotti** [jkitchin/ox-ipynb#41]
Whenever I need a pure \LaTeX environment, I'm used to use it with 
```
#+begin_export latex
<...>
#+end_export, 
```
as I can freely move to an org-src-mode window, allowing auctex keybindings, yasnippets snippets and such. However, if I export an org file to ipynb with these export blocks, they get supressed from the output. Is there a workaround (other than removing those block headers)? Thanks.

**Comment by jkitchin** [comment]
I don't see a way around that, that is pretty specific to latex exports. The only thing I can think of is a pre-processing hook to replace those blocks with something else that looks more like equations or latex environments.

**Comment by Morazotti** [comment]
Well, that's all right. The `export` blocks are used together with `\begin{align}`, so there is little hassle to remove all block structure from file using macros, while keeping latex stuff. In any case, thank you! Big fan of the project, and the other various utilities.
