### ISSUE TITLE
Null metadata prevents notebooks from loading

### ISSUE THREAD

**Issue by robertutterback** [jkitchin/ox-ipynb#43]
This is possibly related to #42, except I have already installed `jupyter_console` and `jupyter_client`.

I get the below error when trying to open an exported notebook:

![image](https://user-images.githubusercontent.com/2722476/186024074-eff05fa8-0e45-482e-bec4-7b19b6f888b9.png)

I was trying to export the `example.org` file in the repo, with the exception that I removed the internal link (otherwise emacs says its unable to resolve the link and won't export). 

Each of the cells has `"metadata": null`. I don't know much about the Jupyter format, but I guessed that `{}` might work instead of `null` and indeed changing all of those allowed the notebook to load.

# env

```bash
$ jupyter --version
Selected Jupyter core packages...
IPython          : 7.26.0
ipykernel        : 6.15.1
ipywidgets       : 7.6.3
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.10.2
jupyterlab       : 3.1.2
nbclient         : 0.5.3
nbconvert        : 6.1.0
nbformat         : 5.1.3
notebook         : 6.4.0
qtconsole        : not installed
traitlets        : 5.3.0

$ emacs --version
GNU Emacs 26.3
```

`Org mode version 9.5.4 (9.5.4-ge0b05b @ /home/rob/.emacs.d/elpa/org-9.5.4/) `

**Comment by jkitchin** [comment]
hm. something seems wrong. I can't reproduce this. when I export the example, I get {} not null. 

Your emacs is pretty old. I am not sure that would cause this though. Those metadata fields should be empty hash tables.

what happens when you run this code:

```
#+BEGIN_SRC emacs-lisp
(json-encode (make-hash-table))
#+END_SRC

#+RESULTS:
: {}
```

**Comment by robertutterback** [comment]
I get `{}`.

**Comment by robertutterback** [comment]
Weirdly, updating Emacs seemed to fix the issue, despite `(json-encode (make-hash-table))` working fine. I'm not sure what was happening.
