### ISSUE TITLE
What's wrong with using tables as a data source for ipython blocks?

### ISSUE THREAD

**Issue by apnewberry** [jkitchin/ox-ipynb#7]
The [example](https://github.com/jkitchin/ox-ipynb/blob/master/example.ipynb) says 

>  Note that you probably should not use the tables as data sources to code blocks because the ipython notebook does not support that.

Sacha Chua [demos it ](http://sachachua.com/blog/2015/01/getting-data-org-mode-tables/) in R, so I tried doing it in ipython and it seemed to work great. 

What do I need to worry about if I'm doing this? What relevant feature is missing from org or jupyter that I should follow?

**Comment by johnrkitchin** [comment]
It should work fine in orgmode. What won't work fine is if you export to a jupyter notebook. They have no concept of data from tables.

**Comment by apnewberry** [comment]
Oh I see, yes, that fails. Thanks.
